# Standalone build for this project, as the monorepo sees it. Generated by
# platform/tangled/publish/gen-project.nu; edit that template, not this file.
#
# nix-workspace is a path here, so the monorepo can evaluate its own change to
# it without publishing first, and so the root flake can take this as an
# input and check that it still builds. The published repo gets the same file
# with a Tangled URL, mapped over this one by josh.
#
# The relative path only resolves when this flake is reached through the repo
# root: as a root input, or `nix eval '.?dir=<this directory>#...'`.
{
  description = "A PipeWire-compatible multimedia graph daemon written in Rust";

  inputs.workspace.url = "path:../../../platform/nix/workspace";

  outputs = inputs:
    inputs.workspace ./. {
      name = "oxidized-pipewire";
      description = "A PipeWire-compatible multimedia graph daemon written in Rust";
      aliases = {
        "pipewire" = "rust-pipewire";
        "pipewire-pulse" = "rust-pipewire";
        "pipewire-aes67" = "rust-pipewire";
        "pipewire-avb" = "rust-pipewire";
        "pipewire-vulkan" = "rust-pipewire";
        "pw-cli" = "rust-pipewire";
        "pw-mon" = "rust-pipewire";
        "pw-dump" = "rust-pipewire";
        "pw-link" = "rust-pipewire";
        "pw-metadata" = "rust-pipewire";
        "pw-loopback" = "rust-pipewire";
        "pw-config" = "rust-pipewire";
        "pw-cat" = "rust-pipewire";
        "pw-play" = "rust-pipewire";
        "pw-record" = "rust-pipewire";
        "pw-dot" = "rust-pipewire";
        "pw-top" = "rust-pipewire";
        "pw-profiler" = "rust-pipewire";
        "pw-reserve" = "rust-pipewire";
        "pw-container" = "rust-pipewire";
        "pw-mididump" = "rust-pipewire";
        "pw-midiplay" = "rust-pipewire";
        "pw-midirecord" = "rust-pipewire";
        "pw-midi2play" = "rust-pipewire";
        "pw-midi2record" = "rust-pipewire";
        "pw-sysex" = "rust-pipewire";
        "pw-dsdplay" = "rust-pipewire";
        "pw-encplay" = "rust-pipewire";
        "pw-v4l2" = "rust-pipewire";
        "spa-json-dump" = "rust-pipewire";
        "spa-inspect" = "rust-pipewire";
        "spa-monitor" = "rust-pipewire";
        "spa-acp-tool" = "rust-pipewire";
        "spa-resample" = "rust-pipewire";
      };
    };
}
